version: '3.8'
services: 
  indy-sdk:
    build: .
    image: jrayback/indy-sdk:latest
    container_name: indy-sdk
    volumes:
    - ".:/root"
    stdin_open: true
    tty: true
    command: /bin/bash
